#!/bin/bash

####Váriáveis####
RAIZ=/work
#DISCOS=/work/disks
D_1=/work/disks/8pd1
D_2=/work/disks/8pd2
D_3=/work/disks/8pd3
D_4=/work/disks/8pd4
D_5=/work/disks/8pd5
D_6=/work/disks/8pd6
D_7=/work/disks/8pd7
D_8=/work/disks/8pd8
D_160=/work/rack/160
D_163=/work/rack/163
D_8PRETA=/work/gavetas/8preta
D_5PRETA=/work/gavetas/5preta
D_2SILVER=/work/gavetas/2prata
O_160=//192.168.100.160/dados
O_163=//192.168.100.163/dados
LIMITE=100G
O_SKIPPER=/work/rack/163/Skipper/
D_SKIPPER=/work/all/Dados
O_GDRIVE=/work/rack/160/remoto/
D_GDRIVE=/work/all/GDrive
PASTAS='/etc/scripts /etc/samba/smb.conf /etc/rc.local /etc/ssh/sshd_config /root/.bashrc /etc/vsftpd.conf'
SAMBA='/etc/samba/smb.conf'
LOG='/work/all/log.txt'
FTP='/etc/vsftpd.conf'
####Váriáveis####


####Funções####


function f_hora() 
{
	ntpdate pool.ntp.org
}

function f_atualiza() 
{
	apt-get update && apt-get upgrade -y && apt-get autoremove && apt-get autoclean && apt-get clean
}


function f_monta8() 
{

	###monta unidades###
	#mount -L 5pd1 /work/disks/5pd1
	#mount -L 5pd2 /work/disks/5pd2
	#mount -L 5pd3 /work/disks/5pd3
	#mount -L 5pd4 /work/disks/5pd4
	#mount -L 5pd5 /work/disks/5pd5
	mount -L 8pd1 /work/disks/8pd1
	mount -L 8pd2 /work/disks/8pd2
	mount -L 8pd3 /work/disks/8pd3
	mount -L 8pd4 /work/disks/8pd4
	mount -L 8pd5 /work/disks/8pd5
	mount -L 8pd6 /work/disks/8pd6
	mount -L 8pd7 /work/disks/8pd7
	mount -L 8pd8 /work/disks/8pd8
	#mount -L 2sd1 /work/disks/2sd1
	#mount -L 2sd2 /work/disks/2sd2
	###monta unidades###

}



function f_desmonta() 
{
	cd /
	umount -f $D_160
	umount -f $D_163
	umount -f $D_8PRETA
	umount -f $D_5PRETA
	umount -f $D_2SILVER
	#umount /work/disks/5pd[1-5]
	#umount /work/disks/8pd[1-8]
	#umount /work/disks/2sd[1-2]
	#umount /work/gavetas/5preta
	#umount /work/gavetas/8preta
	#umount /work/gavetas/2prata
	#umount /work/rack/16[0-9]
lsu
}

function f_perm() 
{
	chmod -R 777 $RAIZ
}

function f_NAS() 
{
	mount -t cifs -o rw,guest,vers=2.0 $O_160 $D_160
	mount -t cifs -o rw,guest,vers=2.0 $O_163 $D_163
}

function f_junta() 
{
	mhddfs $D_1,$D_2,$D_3,$D_4,$D_5,$D_6,$D_7,$D_8 $D_8PRETA -o allow_other -o mlimit=LIMITE
#	mhddfs $D_1,$D_2,$D_3,$D_4,$D_5 $D_5PRETA -o allow_other -o mlimit=LIMITE
#	mhddfs $D_6,$D_7 $D_2SILVER -o allow_other -o mlimit=LIMITE
}

function f_sync() 
{
	rsync -avh --delete --info=progress2 $O_SKIPPER $D_SKIPPER
	rsync -avh --delete --info=progress2 $O_GDRIVE $D_GDRIVE
}


function f_ftpON() 
{
	/etc/init.d/vsftpd start
}

function f_ftpOFF() 
{
	/etc/init.d/vsftpd stop
}


function f_samba() 
{
	cat > $SAMBA <<EOT 

[global]
workgroup = workgroup
server role = standalone server
security = user
map to guest = Bad Password

[8preta]
path = /work/gavetas/8preta
writable = yes
browseable = yes
guest ok = yes
create mask = 0777
directory mask = 0777

[5preta]
path = /work/gavetas/5preta
writable = yes
browseable = yes
guest ok = yes
create mask = 0777
directory mask = 0777

[2prata]
path = /work/gavetas/2prata
writable = yes
browseable = yes
guest ok = yes
create mask = 0777
directory mask = 0777

[rack]
path = /work/rack
writable = yes
browseable = yes
guest ok = yes
create mask = 0777
directory mask = 0777

[disks]
path = /work/disks
writable = yes
browseable = yes
guest ok = yes
create mask = 0777
directory mask = 0777

[scripts]
path = /etc/scripts
writable = yes
browseable = yes
guest ok = yes
create mask = 0777
directory mask = 0777
EOT
}

function f_ftp() 
	{
		cat > $FTP <<EOT 

listen=yes
anonymous_enable=NO
local_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES
idle_session_timeout=600
ftpd_banner=Welcome to Underground FTP service.
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd
rsa_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
rsa_private_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
ssl_enable=NO
tcp_wrappers=YES
local_root=/work
EOT
	}	


####Funções####

case $1 in 
	
	born)
		echo -n  Configurando servicos ...
		f_ftp
		f_samba
		echo Concluido.

	;;


	atualiza)
		echo -n  Atualizando Sistema Operacional Completo ...
		f_hora
		f_atualiza
		echo Concluido.

	;;

	perm)
		echo -n  Ajustando permissao de $DISCOS ...
		f_perm
		echo Concluido.

	;;

	
	rack)
		echo -n  Montando discos NAS e iniciando servicos ...
		f_desmonta
		f_hora
		f_perm
		f_NAS
		f_ftpON
		echo Concluido.

	;;

	restart)
		echo -n  Reiniciando sistema Completo ...
		f_hora
		reboot	
		echo Concluido.

	;;

	off)
		echo -n  Desmontando discos NAS e parando servicos ...
		f_hora
		f_ftpOFF
		f_desmonta
		f_perm
		echo Concluido.

	;;

	
	on)
		echo -n  Monta DISCOS LOCAIS em JBOD ...
		f_hora		
		f_desmonta
		f_monta8
		f_perm
		f_junta
		echo Concluido.

	;;


	sync)
		echo -n  Sincronizando discos ...
		f_hora
		f_perm
		f_junta
		f_NAS
		f_sync
		f_perm
		f_desmonta
		echo Concluido.

	;;


	



	*)
		echo Uso Incorreto. {Tente start ou stop ou restart}
		exit 1

esac
