#!/bin/bash

####Váriáveis####
RAIZ=/work
#DISCOS=/work/disks
D_1=/work/disks/8pd1
D_2=/work/disks/8pd2
D_3=/work/disks/8pd3
D_4=/work/disks/8pd4
D_5=/work/disks/8pd5
D_6=/work/disks/8pd6
D_7=/work/disks/8pd7
D_8=/work/disks/8pd8
D_160=/work/rack/160
D_163=/work/rack/163
D_8PRETA=/work/gavetas/8preta
D_5PRETA=/work/gavetas/5preta
D_2SILVER=/work/gavetas/2prata
O_160=//192.168.100.160/dados
O_163=//192.168.100.163/dados
LIMITE=100G
O_SKIPPER=/work/rack/163/Skipper/
D_SKIPPER=/work/gavetas/8preta/Dados
O_GDRIVE=/work/rack/160/remoto/
D_GDRIVE=/work/gavetas/8preta/GDrive
SAMBA='/etc/samba/smb.conf'
FTP='/etc/vsftpd.conf'
DATA=`date +%d%m%Y`
LOG=/work/$DATA-sync.txt

####Váriáveis####


####Funções####


function f_hora() 
{
	ntpdate pool.ntp.org
}

function f_atualiza() 
{
	apt-get update && apt-get upgrade -y && apt-get autoremove && apt-get autoclean && apt-get clean
	cd /etc/scripts
	DATA=`date +%d%m%Y` 
	mv tools $DATA.tools.old
	chmod u-x *.old
	curl https://raw.githubusercontent.com/atedim/start/main/tools -o tools
	chmod u+x tools
}


function f_monta8() 
{
	mount -L 8pd1 /work/disks/8pd1
	mount -L 8pd2 /work/disks/8pd2
	mount -L 8pd3 /work/disks/8pd3
	mount -L 8pd4 /work/disks/8pd4
	mount -L 8pd5 /work/disks/8pd5
	mount -L 8pd6 /work/disks/8pd6
	mount -L 8pd7 /work/disks/8pd7
	mount -L 8pd8 /work/disks/8pd8
}

function f_monta5() 
{
	mount -L 5pd1 /work/disks/5pd1
	mount -L 5pd2 /work/disks/5pd2
	mount -L 5pd3 /work/disks/5pd3
	mount -L 5pd4 /work/disks/5pd4
	mount -L 5pd5 /work/disks/5pd5
}

function f_monta2() 
{
	mount -L 2sd1 /work/disks/2sd1
	mount -L 2sd2 /work/disks/2sd2
}


function f_desmonta() 
{
	cd /
	umount -f $D_160
	umount -f $D_163
	umount -f $D_8PRETA
	#umount -f $D_5PRETA
	#umount -f $D_2SILVER
	#umount /work/disks/5pd[1-5]
	umount /work/disks/8pd[1-8]
	#umount /work/disks/2sd[1-2]
	#umount /work/rack/16[0-9]
}

function f_perm() 
{
	chmod -R 777 $RAIZ
}

function f_NAS() 
{
	mount -t cifs -o rw,guest,vers=2.0 $O_160 $D_160
	mount -t cifs -o rw,guest,vers=2.0 $O_163 $D_163
}

function f_junta8() 
{
	mhddfs $D_1,$D_2,$D_3,$D_4,$D_5,$D_6,$D_7,$D_8 $D_8PRETA -o allow_other -o mlimit=LIMITE
}

#function f_junta5() 
#{
#	mhddfs $D_1,$D_2,$D_3,$D_4,$D_5 $D_5PRETA -o allow_other -o mlimit=LIMITE
#}


#function f_junta2() 
#{
#	mhddfs $D_6,$D_7 $D_2SILVER -o allow_other -o mlimit=LIMITE
#}

	
function f_info() 
{

	clear 
	cpu=$(</sys/class/thermal/thermal_zone0/temp)
	max=$(</sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq)
	min=$(</sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq)
	curr=$(</sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq)
	echo "$(date) @ $(hostname)"
	echo " "
	echo "############################################"
	echo "#Dispositivo#"
	echo "#############"
	echo " "
	echo "$(tr -d '\0' </proc/device-tree/model)"
	echo "IP = $(hostname -I)"
	echo " "
	echo "############################################"
	echo "#Temperatura#"
	echo "#############"
	echo " "
	echo "CPU => $((cpu/1000))'C"
	echo " "
	echo "############################################"
	echo "#Frequencia#"
	echo "############"
	echo " "
	echo "CPU Max => $((max/1000)) Mhz"
	echo "CPU Min => $((min/1000)) Mhz"
	echo "CPU Atual => $((curr/1000)) Mhz"
	echo " "
	echo "############################################"
	echo "#Servicos#"
	echo "##########"
	echo " "
	echo "FTP = $(systemctl show -p ActiveState vsftpd.service  | cut -d'=' -f2)"
	echo "SMB = $(systemctl show -p ActiveState smbd  | cut -d'=' -f2)"
	echo " "
	echo "############################################"
	echo "#Unidades Montadas#"
	echo "###################"
	echo " "
	echo "MobyDick = $(mountpoint -q /work/rack/160 && echo "montado" || echo "desmontado")"
	echo "Greivous = $(mountpoint -q /work/rack/163 && echo "montado" || echo "desmontado")"
	echo "Gaveta8 = $(mountpoint -q /work/gavetas/8preta && echo "montado" || echo "desmontado")"
	echo " "
	echo "############################################"
	echo " "
}


function f_sync() 
{
	echo "Inicio Sync" >> $LOG
	echo `date`  >> $LOG
	rsync -avh --delete $O_SKIPPER $D_SKIPPER >> $LOG
	rsync -avh --delete $O_GDRIVE $D_GDRIVE >> $LOG
	echo `date`  >> $LOG
	echo "Fim Sync" >> $LOG
	echo "     " >> $LOG
	cp -fav $LOG $O_GDRIVE/Sync/$LOG
}


function f_ftpON() 
{
	/etc/init.d/vsftpd start
}

function f_ftpOFF() 
{
	/etc/init.d/vsftpd stop
}

function f_samba() 
{
	cat > $SAMBA <<EOT 

[global]
workgroup = workgroup
server role = standalone server
security = user
map to guest = Bad Password

[8preta]
path = /work/gavetas/8preta
writable = yes
browseable = yes
guest ok = yes
create mask = 0777
directory mask = 0777

#[5preta]
#path = /work/gavetas/5preta
#writable = yes
#browseable = yes
#guest ok = yes
#create mask = 0777
#directory mask = 0777

#[2prata]
#path = /work/gavetas/2prata
#writable = yes
#browseable = yes
#guest ok = yes
#create mask = 0777
#directory mask = 0777

[rack]
path = /work/rack
writable = yes
browseable = yes
guest ok = yes
create mask = 0777
directory mask = 0777

[disks]
path = /work/disks
writable = yes
browseable = no
guest ok = yes
create mask = 0777
directory mask = 0777

[local]
path = /work/local
writable = yes
browseable = yes
guest ok = yes
create mask = 0777
directory mask = 0777

[scripts]
path = /etc/scripts
writable = yes
browseable = yes
guest ok = yes
create mask = 0777
directory mask = 0777
EOT
}

function f_ftp() 
	{
		cat > $FTP <<EOT 

listen=yes
anonymous_enable=NO
local_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES
idle_session_timeout=600
ftpd_banner=Welcome to Underground FTP service.
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd
rsa_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
rsa_private_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
ssl_enable=NO
tcp_wrappers=YES
local_root=/work
EOT
	}	

function f_entropia() 
{

###Nao alterar aqui colocar mudanças em start.sh

##atualiza sources###
apt-get update && apt-get upgrade -y && apt-get autoremove && apt-get autoclean && apt-get clean
##atualiza sources###


###instala basicos###
apt-get install ntpdate rcconf mc rsync cifs-utils samba mhddfs htop ntfs-3g exfat-fuse exfat-utils iptraf net-tools ncdu screen vsftpd -y
###instala basicos###


###Atualiza data e hora###
unlink /etc/localtime
ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
ntpdate pool.ntp.org
###Atualiza data e hora###


##limpa espaço###
apt-get autoremove && apt-get autoclean && apt-get clean
##limpa espaço###


###backup inicial###
DATA=`date +%d%m%Y` 
cd / && tar zcvfp $DATA.etc.ORI.tgz /etc
###backup inicial###


###Ajusta ssh###
sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
/etc/init.d/ssh restart
###Ajusta ssh###


###Insere Script to PATH###
sed -i -e '$a\' ~/.bashrc && echo 'export PATH=$PATH:/etc/scripts' >>~/.bashrc && sed -i -e '$a\' ~/.bashrc
###Insere Script to PATH###


###Muda senha Root###
echo -e "123456\n123456" | passwd root
###Muda senha Root###

###Cria Diretórios###
mkdir -p /work/all
mkdir -p /work/disks/2sd{1,2}
mkdir -p /work/disks/5pd{1..5}
mkdir -p /work/disks/8pd{1..8}
mkdir -p /work/gavetas/2prata
mkdir -p /work/gavetas/{5,8}preta
mkdir -p /work/rack/16{0..9}
mkdir -p /work/local
chmod -R 777 /work
###Cria Diretórios###


###Cria usuario FTP###
useradd -p $(openssl passwd -1 mustelide) -m ftplogan
#redefine senha caso ja exista
echo -e "mustelide\nmustelide" | passwd ftplogan
###Cria usuario FTP###

###Desabilita auto-start FTP###
systemctl disable vsftpd.service
###Desabilita auto-start FTP###

	
}

####Funções####

case $1 in 
	
	entropia)
		echo -n  Fazendo o que o Start.sh faz ...
		echo -n  Pausa de 5 segundos, cancele caso tenha duvidas.
		sleep 5
		f_entropia
		echo Concluido.
	;;


	born)
		echo -n  Configurando servicos ...
		f_ftp
		f_samba
		echo Concluido.

	;;


	update)
		echo -n  Atualizando Sistema Operacional Completo ...
		f_hora
		f_atualiza
		echo Concluido.

	;;

		
	rack)
		echo -n  Montando discos NAS e iniciando servicos ...
		f_desmonta
		f_hora
		f_perm
		f_NAS
		f_ftpON
		echo Concluido.

	;;

	restart)
		echo -n  Reiniciando sistema Completo ...
		f_hora
		reboot	
		echo Concluido.

	;;

	off)
		echo -n  Desmontando discos NAS e parando servicos ...
		f_hora
		f_ftpOFF
		f_desmonta
		f_perm
		echo Concluido.

	;;

	
	on)
		echo -n  Monta DISCOS LOCAIS em JBOD ...
		f_hora		
		f_desmonta
		f_monta8
		#f_perm
		f_junta8
		echo Concluido.

	;;


	sync)
		echo -n  Sincronizando discos ...
		f_hora
		f_desmonta		
		f_perm
		f_monta8
		f_junta8
		f_NAS
		f_sync
		f_perm
		f_desmonta
		echo Concluido.

	;;

	info)
		#echo -n  Obtendo Info do Sistema ...
		f_info
		
	;;


	*)
		clear
		echo 
		echo Tools ver 0.61 13042021
		echo 
		echo 
		echo  entropia = Like start.sh 
		echo 
		echo  born = Cria arquivos do FTP e SMB
		echo 
		echo  update = Atualiza TOTALMENTE o Sistema operacional
		echo
		echo  rack = Monta storages do NAS e FTP
		echo
		echo  on = Monta DISCOS LOCAIS em JBOD
		echo
		echo  off = Desmonta DISCOS LOCAIS em JBOD e para FTP
		echo
		echo  restart = Reinicia Sistema Operacional
		echo
		echo  sync = Sincroniza Storages
		echo
		echo  info = Exibe Info do Sistema
		echo
		exit 1

esac
